services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: giuliano
      POSTGRES_PASSWORD: nossapadaria
      POSTGRES_DB: padaria
