import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const products = [
  // ACHOCOLATADOS - stock 0 e desativados
  {
    name: "chocolate em pó",
    category: "achocolatados",
    price: 6.49,
    description: "Chocolate em pó para bebidas e receitas.",
    imageUrl: "/fotos/achocolatados/chocolate em po.png",
    stock: 3,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "creme de leite",
    category: "achocolatados",
    price: 3.99,
    description: "Creme de leite fresco para diversas preparações.",
    imageUrl: "/fotos/achocolatados/creme de leite.png",
    stock: 0,
    isActive: false,
    isVitrine: false,
  },
  {
    name: "leite em pó",
    category: "achocolatados",
    price: 4.99,
    description: "Leite em pó de alta qualidade e sabor.",
    imageUrl: "/fotos/achocolatados/leite em po.png",
    stock: 30,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "nescau",
    category: "achocolatados",
    price: 4.49,
    description: "Achocolatado em pó saboroso e prático.",
    imageUrl: "/fotos/achocolatados/nescau.png",
    stock: 40,
    isActive: true,
    isVitrine: false,
  },

  // BEBIDAS - stock 10 e ativos
  {
    name: "café personalizado",
    category: "bebidas",
    price: 6.99,
    description: "Café personalizado para o seu momento.",
    imageUrl: "/fotos/bebidas/cafre personalizado.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "capuccino",
    category: "bebidas",
    price: 5.99,
    description: "Delicioso capuccino cremoso e quentinho.",
    imageUrl: "/fotos/bebidas/caputino-removebg-preview.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "coca-cola",
    category: "bebidas",
    price: 3.99,
    description: "Refrigerante clássico para qualquer ocasião.",
    imageUrl: "/fotos/bebidas/coca-removebg-preview.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "gatorade",
    category: "bebidas",
    price: 4.99,
    description: "Bebida isotônica para hidratação rápida.",
    imageUrl: "/fotos/bebidas/gatorade.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "leite",
    category: "bebidas",
    price: 3.49,
    description: "Leite fresco e nutritivo.",
    imageUrl: "/fotos/bebidas/LEITE-removebg-preview.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "refrigerante",
    category: "bebidas",
    price: 3.99,
    description: "Refrigerantes variados para sua escolha.",
    imageUrl: "/fotos/bebidas/refrigerantes.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },

  // BOLOS E TORTAS - stock 10 e ativos (adicionando novos)
  {
    name: "bola de morango",
    category: "bolos-e-tortas",
    price: 14.99,
    description: "Bolo de morango fresco e saboroso.",
    imageUrl: "/fotos/bolos-e-tortas/bola de morango.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "bolo de chocolate com jabuticaba",
    category: "bolos-e-tortas",
    price: 16.99,
    description: "Bolo de chocolate com sabor especial de jabuticaba.",
    imageUrl: "/fotos/bolos-e-tortas/bolo de chocolate com jabuticaba.jpg",
    stock: 10,
    isActive: true,
    isVitrine: true,
  },
  {
    name: "bolo de oreo",
    category: "bolos-e-tortas",
    price: 17.99,
    description: "Bolo cremoso com pedaços de Oreo.",
    imageUrl: "/fotos/bolos-e-tortas/bolo de oreo.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "bolo de queijo com jabuticaba",
    category: "bolos-e-tortas",
    price: 18.99,
    description: "Bolo de queijo com jabuticaba, sabor único.",
    imageUrl: "/fotos/bolos-e-tortas/bolo de queijo com jabuticaba.jpg",
    stock: 10,
    isActive: true,
    isVitrine: true,
  },
  {
    name: "bolo de chocolate",
    category: "bolos-e-tortas",
    price: 13.99,
    description: "Bolo de chocolate delicioso e macio.",
    imageUrl: "/fotos/bolos-e-tortas/bolo_de_chocolate-removebg-preview (1).png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "torta de jabuticaba e limão",
    category: "bolos-e-tortas",
    price: 15.99,
    description: "Torta cítrica com jabuticaba e limão.",
    imageUrl: "/fotos/bolos-e-tortas/torta de jabuticaba e limao.avif",
    stock: 10,
    isActive: true,
    isVitrine: true,
  },
  {
    name: "torta de frutas",
    category: "bolos-e-tortas",
    price: 15.99,
    description: "Torta com frutas frescas e creme suave.",
    imageUrl: "/fotos/bolos-e-tortas/torta_de_frutas-removebg-preview.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },

  // COMBOS - stock 10 e ativos
  {
    name: "combo café da manhã",
    category: "combos",
    price: 19.99,
    description: "Combo especial para seu café da manhã.",
    imageUrl: "/fotos/combos/combo cafe da manha.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "combo de salgados",
    category: "combos",
    price: 24.99,
    description: "Variedade de salgados para seu lanche.",
    imageUrl: "/fotos/combos/combo de salgados.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },

  // DOCES - stock 10 e ativos
  {
    name: "doce de leite",
    category: "doces",
    price: 5.99,
    description: "Doce de leite caseiro e cremoso.",
    imageUrl: "/fotos/doces/doce de leite.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "macarone",
    category: "doces",
    price: 4.99,
    description: "Macarons delicados e coloridos.",
    imageUrl: "/fotos/doces/macarone-removebg-preview.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "milkshake",
    category: "doces",
    price: 7.99,
    description: "Milkshake gelado com sabor intenso.",
    imageUrl: "/fotos/doces/milkshake.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "panqueca de chocolate e sorvete",
    category: "doces",
    price: 11.99,
    description: "Panqueca doce com chocolate e sorvete.",
    imageUrl: "/fotos/doces/panqueca de chocolate e sorrvete.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "rosquinhas",
    category: "doces",
    price: 5.99,
    description: "Rosquinhas fresquinhas para o lanche.",
    imageUrl: "/fotos/doces/rosquinhas.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },

  // PÃES - stock 10 e ativos
  {
    name: "croissant",
    category: "paes",
    price: 4.49,
    description: "Croissant amanteigado e folhado.",
    imageUrl: "/fotos/paes/croassant.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "pães de queijo",
    category: "paes",
    price: 5.49,
    description: "Pães de queijo quentinhos e saborosos.",
    imageUrl: "/fotos/paes/paes de queijo.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "pão doce",
    category: "paes",
    price: 3.99,
    description: "Pão doce macio com toque especial.",
    imageUrl: "/fotos/paes/pao doce.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "pão francês",
    category: "paes",
    price: 2.99,
    description: "Pão francês fresquinho do dia.",
    imageUrl: "/fotos/paes/pao frances.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },

  // QUEIJOS - stock 10 e ativos
  {
    name: "queijo branco caseiro",
    category: "queijos",
    price: 9.99,
    description: "Queijo branco caseiro, sabor tradicional.",
    imageUrl: "/fotos/queijos/queijo branco caseiro.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "queijo coalho",
    category: "queijos",
    price: 11.99,
    description: "Queijo coalho perfeito para churrasco.",
    imageUrl: "/fotos/queijos/queijo coalho.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "queijo gorgonzola",
    category: "queijos",
    price: 14.99,
    description: "Queijo gorgonzola forte e cremoso.",
    imageUrl: "/fotos/queijos/QUEIJO gorgonzola.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "queijo gourmet",
    category: "queijos",
    price: 13.99,
    description: "Queijo gourmet para paladares exigentes.",
    imageUrl: "/fotos/queijos/queijo goutmet.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "queijo minas",
    category: "queijos",
    price: 10.99,
    description: "Queijo minas tradicional mineiro.",
    imageUrl: "/fotos/queijos/queijo minas.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },

  // SALGADOS - stock 10 e ativos
  {
    name: "coxinha",
    category: "salgados",
    price: 4.99,
    description: "Coxinha crocante e recheada.",
    imageUrl: "/fotos/salgados/coxinha-removebg-preview.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "coxinhas",
    category: "salgados",
    price: 5.49,
    description: "Coxinhas fresquinhas para seu lanche.",
    imageUrl: "/fotos/salgados/coxinhas.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "kibis",
    category: "salgados",
    price: 5.99,
    description: "Kibis crocantes e saborosos.",
    imageUrl: "/fotos/salgados/kibis.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
  {
    name: "pastel",
    category: "salgados",
    price: 4.49,
    description: "Pastel quentinho e recheado.",
    imageUrl: "/fotos/salgados/pastel.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },

  // SANDUÍCHES - stock 10 e ativos
  {
    name: "sanduíche alface tomate",
    category: "sanduiches",
    price: 6.99,
    description: "Sanduíche leve com alface e tomate.",
    imageUrl: "/fotos/sanduíches/sanduiche alface tomate.png",
    stock: 10,
    isActive: true,
    isVitrine: false,
  },
];


export async  function ProductsSedd() {
  console.log("Starting seed...");

  for (const product of products) {
    try {
      await prisma.product.create({ data: product });
      console.log(`Created product: ${product.name}`);
    } catch (error) {
      console.error(`Failed to create product: ${product.name}`, error);
    }
  }

  console.log("Seed finished.");
 
}


